# Generated by Django 3.0.8 on 2020-09-02 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='email',
        ),
    ]
