# Generated by Django 3.0.8 on 2020-09-17 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_pharmaadmin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='pharmacy',
            options={'ordering': ['id']},
        ),
    ]
