# Generated by Django 3.2 on 2021-04-22 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('user_session', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('total_price', models.FloatField(default=0.0)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.cart')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('address', models.CharField(max_length=100)),
                ('address_opt', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=25)),
                ('woreda', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
                ('note', models.TextField()),
                ('date_time', models.DateTimeField(verbose_name='Placement Time')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='store.cart')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customer')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=10)),
                ('rejection_reason', models.TextField()),
                ('cart_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.cartitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.pharmacy')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
                ('vendor', models.CharField(max_length=30)),
                ('stock', models.IntegerField(default=0)),
                ('expiry_date', models.DateField()),
                ('production_date', models.DateField()),
                ('batch_number', models.CharField(max_length=100)),
                ('requires_prescription', models.BooleanField()),
                ('image', models.ImageField(default='default_med.png', upload_to='products/')),
                ('active', models.BooleanField(default=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.pharmacy')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='EFDA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=35, unique=True)),
                ('expiry_date', models.DateTimeField()),
                ('in_use', models.BooleanField(default=False)),
                ('med_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.medication')),
            ],
        ),
        migrations.AddField(
            model_name='cartitem',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.medication'),
        ),
    ]
