# Generated by Django 3.0.8 on 2020-08-14 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
                ('vendor', models.CharField(max_length=30)),
                ('stock', models.IntegerField(default=0)),
                ('expiry_date', models.DateField()),
                ('production_date', models.DateField()),
                ('batch_number', models.CharField(max_length=100)),
                ('requires_prescription', models.BooleanField()),
                ('image', models.FilePathField()),
                ('pharmacy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Pharmacy')),
            ],
        ),
    ]
