# Generated by Django 3.0.8 on 2021-04-22 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='image',
            field=models.ImageField(default='default_med.png', upload_to='products'),
        ),
    ]
