# Generated by Django 3.0.8 on 2020-08-15 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='session_id',
            new_name='user_session',
        ),
    ]
