# Generated by Django 3.0.8 on 2020-08-16 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200815_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='cart_id',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='drug_id',
            new_name='drug',
        ),
        migrations.RenameField(
            model_name='medication',
            old_name='pharmacy_id',
            new_name='pharmacy',
        ),
    ]
