# Generated by Django 3.0.8 on 2020-08-19 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('store', '0006_cartitem_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='stock',
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Medication')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Pharmacy')),
            ],
        ),
    ]
