# Generated by Django 3.0.8 on 2020-08-21 08:38

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200819_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_name', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=35)),
                ('last_name', models.CharField(max_length=35)),
                ('address', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=15)),
                ('woreda', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phone_field.models.PhoneField(max_length=31)),
                ('note', models.TextField()),
                ('date_time', models.DateTimeField(verbose_name='Placement Time')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Cart')),
            ],
        ),
    ]
