# Generated by Django 3.0.8 on 2020-08-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_opt',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
