# Generated by Django 3.0.8 on 2020-08-21 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_order_address_opt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.Cart'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='order',
            name='region',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='woreda',
            field=models.IntegerField(),
        ),
    ]
