# Generated by Django 3.0.8 on 2020-08-21 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20200821_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='store.Cart'),
        ),
    ]
