# Generated by Django 3.0.8 on 2020-08-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20200821_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
