# Generated by Django 3.0.8 on 2020-08-24 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('store', '0016_auto_20200824_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='pharmacy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Pharmacy'),
        ),
    ]
