# Generated by Django 3.0.8 on 2020-09-13 13:30

from django.db import migrations, models

import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(default=store.models.OrderStatus['PENDING'], max_length=10),
        ),
    ]
