# Generated by Django 3.0.8 on 2020-09-14 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200902_1818'),
        ('store', '0019_auto_20200913_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
