# Generated by Django 3.0.8 on 2020-09-28 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_auto_20200917_1754'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='medication',
            name='image',
            field=models.ImageField(default='default_med.png', upload_to='products/'),
        ),
    ]
