# Generated by Django 3.0.8 on 2020-10-12 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_orderitem_rejection_reason'),
        ('store', '0022_auto_20200928_1518'),
    ]

    operations = [
    ]
