# Generated by Django 3.0.8 on 2020-10-12 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_merge_20201012_1039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={},
        ),
        migrations.AlterModelOptions(
            name='medication',
            options={'ordering': ['id']},
        ),
    ]
