# Generated by Django 3.0.8 on 2020-10-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_auto_20201012_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
